version: "3.9"
networks:
  reverse-proxy:
    external: true
services:
  coder:
    image: ghcr.io/coder/coder:latest
    user: "1000:131" #groupid needs to be the host's docker group
    networks:
      reverse-proxy:
    ports:
      - "7080:7080"
      - "8787:8787"
      - "13339:13339"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/user/docker/volumes/coder:/home/coder"
    environment:
      CODER_PG_CONNECTION_URL: ${CODER_PG_CONNECTION_URL}
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      #HTTP_PROXY: "192.168.2.3:80"
      #HTTPS_PROXY: "192.168.2.3:443"
      CODER_ACCESS_URL: "https://coder.actuary.dev"
      CODER_WILDCARD_ACCESS_URL: "*.coder.actuary.dev"
      CODER_DERP_FORCE_WEBSOCKETS: "true"
      #group-add: "131" #docker group on host, not sure if this is needed
      CODER_EXTERNAL_AUTH_0_DISPLAY_NAME: "Coder Github Login"
      CODER_EXTERNAL_AUTH_0_DISPLAY_ICON: "https://actuary.llc/images/logo/logo@2x.png"
      CODER_EXTERNAL_AUTH_0_ID: "coder-github-oauth"
      CODER_EXTERNAL_AUTH_0_TYPE: "github"
      CODER_EXTERNAL_AUTH_0_CLIENT_ID: ${CODER_EXTERNAL_AUTH_0_CLIENT_ID}
      CODER_EXTERNAL_AUTH_0_CLIENT_SECRET: ${CODER_EXTERNAL_AUTH_0_CLIENT_SECRET}
      #CODER Authentication
      CODER_DISABLE_PASSWORD_AUTH: "true"
      CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS: "true"
      CODER_OAUTH2_GITHUB_ALLOW_EVERYONE: "true"
      #CODER_OAUTH2_GITHUB_ALLOWED_ORGS: "Actuary-LLC"
      CODER_OAUTH2_GITHUB_CLIENT_ID: ${CODER_OAUTH2_GITHUB_CLIENT_ID}
      CODER_OAUTH2_GITHUB_CLIENT_SECRET: ${CODER_OAUTH2_GITHUB_CLIENT_SECRET}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.coder.rule=Host(`coder.actuary.dev`) || HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.coder.actuary.dev`)"
        - "traefik.http.routers.coder.tls.domains[0].main=coder.actuary.dev"
        - "traefik.http.routers.coder.tls.domains[0].sans=*.coder.actuary.dev"
        - "traefik.http.routers.coder.entrypoints=websecure"
        - "traefik.http.routers.coder.service=coder"
        - "traefik.http.routers.coder.tls.certresolver=myresolver"
        - "traefik.http.services.coder.loadbalancer.server.port=7080"
        - "traefik.http.middlewares.coder.headers.customrequestheaders.Upgrade=websocket"
        - "traefik.http.middlewares.coder.headers.customrequestheaders.Connection=Upgrade"
        ## Middlewares
#        - "traefik.http.routers.coder.middlewares=authentik@file"
